// fillerStrings.js — i18n for the public filler simulator (TH default + EN).
// Pure data + a tiny resolver. No React, no Firebase.
export const STRINGS = {
  th: {
    title: 'ลองจำลองขนาดหลังเสริมฟิลเลอร์',
    sub: 'เลื่อนปรับค่าด้านล่าง แล้วดูขนาดที่ประเมินได้ — เป็นการประมาณคร่าวๆ เพื่อให้นึกภาพออก',
    adjust: 'ปรับค่า',
    length: 'ความยาว',
    baseSize: 'ขนาดเดิม (ลำตัว)',
    condomMode: 'กดไซส์ถุงยาง',
    diaMode: 'เลื่อน Ø',
    totalFiller: 'ฟิลเลอร์ทั้งหมด',
    splitLabel: 'แบ่งฉีด ลำตัว ↔ หัว',
    shaft: 'ลำตัว',
    glans: 'หัว',
    graphic: 'ภาพจำลอง',
    view2d: '2D เหมือนจริง',
    view3d: '3D หมุนได้ ⟳',
    rotateHint: '⟳ ลากเพื่อหมุนดูรอบ · ขยายตาม cc สด',
    resultsHeader: 'ขนาดที่ประเมินได้ (เดิม → ใหม่)',
    resGirth: 'รอบวง (ลำตัว)',
    resDia: 'เส้นผ่านศูนย์กลาง',
    resCondom: 'ถุงยางที่ใส่ได้',
    resGlans: 'ขนาดหัว',
    before: 'เดิม',
    noCondomEffect: 'ไม่มีผลต่อไซส์ถุงยาง',
    sizesUnit: 'ไซส์',
    sameSize: 'ขนาดเดิม',
    note: '⚠ ฟิลเลอร์เพิ่มรอบวง/หัว ไม่เพิ่มความยาว · ลำตัวสั้นกว่า + cc เท่ากัน = รอบวงขึ้นเยอะกว่า · อยู่ได้ ~6–24 เดือน แล้วยุบลงบ้างตามเวลา · ไซส์ถุงยางยึดลำตัว (หัวไม่เกี่ยว) · ค่าประมาณ',
    disclaimer: 'ภาพจำลองนี้เป็นการประมาณการคร่าวๆ เพื่อการศึกษาเท่านั้น ไม่ใช่การรับประกันผลลัพธ์ ผลลัพธ์จริงแตกต่างกันในแต่ละบุคคล ขึ้นกับสภาพผิวหนัง ปริมาณสารเติมเต็ม และเทคนิคการฉีด ฟิลเลอร์สลายตัวได้ — กรุณาปรึกษาแพทย์ก่อนตัดสินใจ',
    unitCm: 'ซม.',
    unitIn: 'นิ้ว',
    cc: 'cc',
  },
  en: {
    title: 'Penile Filler Size Simulator',
    sub: 'Adjust the controls below to see your estimated size — a rough approximation to help you picture it',
    adjust: 'Adjust',
    length: 'Length',
    baseSize: 'Current size (shaft)',
    condomMode: 'Pick condom size',
    diaMode: 'Slide Ø',
    totalFiller: 'Total filler',
    splitLabel: 'Split: shaft ↔ glans',
    shaft: 'Shaft',
    glans: 'Glans',
    graphic: 'Visual',
    view2d: '2D realistic',
    view3d: '3D rotate ⟳',
    rotateHint: '⟳ Drag to rotate · scales with cc live',
    resultsHeader: 'Estimated size (before → after)',
    resGirth: 'Girth (shaft)',
    resDia: 'Diameter',
    resCondom: 'Condom size',
    resGlans: 'Glans size',
    before: 'before',
    noCondomEffect: 'does not affect condom size',
    sizesUnit: 'sizes',
    sameSize: 'same size',
    note: '⚠ Filler adds girth/glans, not length · shorter shaft + same cc = more girth · lasts ~6–24 months then partly settles · condom size follows the shaft (glans excluded) · approximate',
    disclaimer: 'This is a rough illustrative estimate for education only — not a guarantee. Individual results vary with skin elasticity, filler volume and injection technique; HA filler is resorbable. Please consult your physician before any decision.',
    unitCm: 'cm',
    unitIn: 'in',
    cc: 'cc',
  },
};

export function makeT(lang) {
  const dict = STRINGS[lang] || STRINGS.th;
  return (key) => (dict[key] != null ? dict[key] : (STRINGS.th[key] != null ? STRINGS.th[key] : key));
}
