// fillerStrings.js — i18n for the public filler simulator (TH default + EN).
// Formal / clinical register (credible, professional). Pure data + a tiny resolver.
export const STRINGS = {
  th: {
    title: 'เครื่องมือประเมินขนาดภายหลังการฉีดฟิลเลอร์',
    sub: 'ปรับค่าพารามิเตอร์ด้านล่างเพื่อประเมินขนาดโดยประมาณภายหลังการฉีดฟิลเลอร์ ผลลัพธ์เป็นการประมาณการเชิงภาพประกอบเพื่อการศึกษา',
    adjust: 'ปรับค่าพารามิเตอร์',
    length: 'ความยาว',
    baseSize: 'ขนาดเดิม (เส้นรอบวงลำตัว)',
    condomMode: 'เลือกขนาดถุงยางอนามัย',
    diaMode: 'กำหนดเส้นผ่านศูนย์กลาง',
    totalFiller: 'ปริมาณฟิลเลอร์รวม',
    splitLabel: 'สัดส่วนการฉีด: ลำตัว / ส่วนหัว',
    shaft: 'ลำตัว',
    glans: 'ส่วนหัว',
    graphic: 'ภาพประกอบ',
    view2d: '2D เชิงกายวิภาค',
    view3d: '3D (หมุนได้)',
    rotateHint: 'ลากเพื่อหมุนดูรอบด้าน · ปรับขนาดตามปริมาณที่กำหนดแบบเรียลไทม์',
    resultsHeader: 'ผลการประเมินขนาด (เดิม → ภายหลังการฉีด)',
    resGirth: 'เส้นรอบวง (ลำตัว)',
    resDia: 'เส้นผ่านศูนย์กลาง',
    resCondom: 'ขนาดถุงยางอนามัยที่เหมาะสม',
    resGlans: 'ขนาดส่วนหัว',
    before: 'เดิม',
    noCondomEffect: 'ไม่มีผลต่อขนาดถุงยางอนามัย',
    sizesUnit: 'ขนาด',
    sameSize: 'ขนาดเท่าเดิม',
    note: '⚠ ฟิลเลอร์เพิ่มเส้นรอบวงและส่วนหัว แต่ไม่เพิ่มความยาว · ลำตัวที่สั้นกว่าเมื่อใช้ปริมาณเท่ากันจะได้เส้นรอบวงเพิ่มมากกว่า · ฟิลเลอร์คงอยู่ประมาณ 6–24 เดือนแล้วสลายตัวลงตามเวลา · ขนาดถุงยางอนามัยอ้างอิงจากเส้นรอบวงลำตัว (ไม่รวมส่วนหัว) · ค่าทั้งหมดเป็นการประมาณการ',
    disclaimer: 'ภาพประกอบและตัวเลขทั้งหมดเป็นการประมาณการเชิงภาพประกอบเพื่อการศึกษาเท่านั้น มิใช่การรับประกันผลลัพธ์ ผลลัพธ์จริงแตกต่างกันในแต่ละบุคคล ขึ้นอยู่กับสภาพผิวหนัง ปริมาณสารเติมเต็ม และเทคนิคการฉีด สารเติมเต็มชนิดไฮยาลูรอนิกสามารถสลายตัวได้ตามธรรมชาติ กรุณาปรึกษาแพทย์ผู้เชี่ยวชาญก่อนตัดสินใจ',
    unitCm: 'ซม.',
    unitIn: 'นิ้ว',
    cc: 'cc',
    // graphic (2D/3D) labels — i18n so EN mode is fully translated
    g2dAria: 'ภาพประกอบมุมมองด้านข้างและภาพตัดขวาง ก่อนและหลังการฉีดฟิลเลอร์',
    g2dSide: 'มุมมองด้านข้าง',
    g2dCross: 'ภาพตัดขวาง (ลำตัว)',
    g2dLegShaft: '🔴 ลำตัวขยายตามปริมาณฟิลเลอร์ลำตัว',
    g2dLegGlans: '🟠 ส่วนหัวขยายตามปริมาณฟิลเลอร์ส่วนหัว',
    g2dLegKey: 'เส้นประแดง = หลังฉีด · เส้นประจาง = เดิม',
    model3dAria: 'แบบจำลองสามมิติ ลากเพื่อหมุน',
  },
  en: {
    title: 'Penile Filler Size Estimator',
    sub: 'Adjust the parameters below to estimate the approximate dimensions following dermal-filler augmentation. All figures are illustrative estimates provided for educational reference.',
    adjust: 'Parameters',
    length: 'Length',
    baseSize: 'Baseline size (shaft girth)',
    condomMode: 'Select condom size',
    diaMode: 'Set diameter',
    totalFiller: 'Total filler volume',
    splitLabel: 'Injection split: shaft / glans',
    shaft: 'Shaft',
    glans: 'Glans',
    graphic: 'Illustration',
    view2d: '2D anatomical',
    view3d: '3D (rotatable)',
    rotateHint: 'Drag to rotate · scales with the specified volume in real time',
    resultsHeader: 'Estimated dimensions (baseline → post-injection)',
    resGirth: 'Girth (shaft)',
    resDia: 'Diameter',
    resCondom: 'Recommended condom size',
    resGlans: 'Glans size',
    before: 'baseline',
    noCondomEffect: 'does not affect condom size',
    sizesUnit: 'sizes',
    sameSize: 'unchanged',
    note: '⚠ Filler increases girth and glans dimensions, not length · a shorter shaft yields a greater girth increase for the same volume · hyaluronic-acid filler persists for approximately 6–24 months before gradually resorbing · condom size references the shaft girth (excluding the glans) · all values are estimates',
    disclaimer: 'All illustrations and figures are illustrative estimates provided for educational reference only and do not constitute a guarantee of results. Actual outcomes vary between individuals, depending on skin elasticity, filler volume, and injection technique. Hyaluronic-acid filler is naturally resorbable. Please consult a qualified physician before making any decision.',
    unitCm: 'cm',
    unitIn: 'in',
    cc: 'cc',
    g2dAria: 'Side-view and cross-section illustration, before and after filler',
    g2dSide: 'Side view',
    g2dCross: 'Cross-section (shaft)',
    g2dLegShaft: '🔴 Shaft expands with shaft filler',
    g2dLegGlans: '🟠 Glans expands with glans filler',
    g2dLegKey: 'Red dashed = after · faint dashed = baseline',
    model3dAria: '3D model — drag to rotate',
  },
};

export function makeT(lang) {
  const dict = STRINGS[lang] || STRINGS.th;
  return (key) => (dict[key] != null ? dict[key] : (STRINGS.th[key] != null ? STRINGS.th[key] : key));
}
