// fillerStrings.js — i18n for the public filler simulator (TH default + EN).
// Formal / clinical register (credible, professional). Pure data + a tiny resolver.
export const STRINGS = {
  th: {
    title: 'เครื่องมือประเมินขนาดภายหลังการฉีดฟิลเลอร์',
    sub: 'ปรับค่าพารามิเตอร์ด้านล่างเพื่อประเมินขนาดโดยประมาณภายหลังการฉีดฟิลเลอร์ ผลลัพธ์เป็นการประมาณการเชิงภาพประกอบเพื่อช่วยให้เห็นภาพได้ชัดเจนยิ่งขึ้น',
    adjust: 'ปรับค่าพารามิเตอร์',
    length: 'ความยาว',
    baseSize: 'ขนาดเดิม (เส้นรอบวงลำตัว)',
    condomMode: 'เลือกขนาดถุงยางอนามัย',
    diaMode: 'กำหนดเส้นผ่านศูนย์กลาง',
    totalFiller: 'ปริมาณฟิลเลอร์รวม',
    splitLabel: 'สัดส่วนการฉีด: ลำตัว / ส่วนหัว',
    shaft: 'ลำตัว',
    glans: 'ส่วนหัว',
    graphic: 'ภาพประกอบ',
    view2d: '2D เชิงกายวิภาค',
    view3d: '3D (หมุนได้)',
    rotateHint: 'ลากเพื่อหมุนดูรอบด้าน · ปรับขนาดตามปริมาณที่กำหนดแบบเรียลไทม์',
    resultsHeader: 'ผลการประเมินขนาด (เดิม → ภายหลังการฉีด)',
    resGirth: 'เส้นรอบวง (ลำตัว)',
    resDia: 'เส้นผ่านศูนย์กลาง',
    resCondom: 'ขนาดถุงยางอนามัยที่เหมาะสม',
    recommended: 'แนะนำ',
    pickClosest: 'เลือกถุงยางไซส์ใกล้เคียงค่านี้',
    resLength: 'ความยาว (ตอนอ่อน)',
    lengthWarn: 'พยุงไม่ให้หด ไม่ใช่ยืดจริง',
    reviewBtn: 'ดูรีวิวจริง',
    reviewBtnSub: 'ก่อน–หลัง เคสจริง',
    reviewTitle: 'ดูรีวิวเคสจริง',
    reviewSub: 'เลือกแบบที่ต้องการชม · ภาพก่อน–หลังจากเคสจริง',
    refsBtn: 'งานวิจัยอ้างอิง',
    refsBtnSub: 'ที่มาของการคำนวณ',
    refsTitle: 'งานวิจัยที่ใช้คำนวณ',
    refsSub: 'ทุกสูตรอ้างอิงงานวิจัยทางการแพทย์ที่ตีพิมพ์จริง — แตะการ์ดเพื่อเปิดงานวิจัยต้นฉบับ',
    refsUsed: 'ใช้คำนวณ',
    refsNote: 'ค่าทั้งหมดเป็นการประมาณเชิงภาพประกอบ · แหล่งอ้างอิงถูกตรวจสอบที่มาแล้ว (2026)',
    reviewCircum: 'แบบขลิบ',
    reviewNocircum: 'แบบไม่ขลิบ',
    resGlans: 'ขนาดส่วนหัว',
    before: 'เดิม',
    noCondomEffect: 'ไม่มีผลต่อขนาดถุงยางอนามัย',
    sizesUnit: 'ขนาด',
    sameSize: 'ขนาดเท่าเดิม',
    beyondStd: 'เกินมาตรฐาน 🔥',
    rangeLegend: 'ค่าซ้าย = ระยะคงตัว · ค่าขวา = ขนาดใหญ่ที่สุด(ช่วงแรก)',
    note: 'ฟิลเลอร์เพิ่มเส้นรอบวงและส่วนหัว · เพิ่มความยาวตอนอ่อน ~+1.6 ซม. (ฟิลเลอร์ช่วยพยุงไม่ให้หดเข้า ไม่ใช่ยืดออกจริง) · ลำตัวที่สั้นกว่าเมื่อใช้ปริมาณเท่ากันจะได้เส้นรอบวงเพิ่มมากกว่า · คงอยู่ประมาณ 12–18 เดือนแล้วสลายตัวลงตามเวลา · ขนาดถุงยางอนามัยอ้างอิงจากเส้นรอบวงลำตัว · ค่าทั้งหมดเป็นการประมาณการ ±~1 ซม.',
    disclaimer: 'ภาพประกอบและตัวเลขทั้งหมดเป็นการประมาณการเชิงภาพประกอบเพื่อการศึกษาเท่านั้น มิใช่การรับประกันผลลัพธ์ ผลลัพธ์จริงแตกต่างกันในแต่ละบุคคล ขึ้นอยู่กับสภาพผิวหนัง ปริมาณสารเติมเต็ม และเทคนิคการฉีด สารเติมเต็มชนิดไฮยาลูรอนิกสามารถสลายตัวได้ตามธรรมชาติ กรุณาปรึกษาแพทย์ผู้เชี่ยวชาญก่อนตัดสินใจ',
    unitCm: 'ซม.',
    unitIn: 'นิ้ว',
    cc: 'cc',
    glansBase: 'ขนาดหัวเริ่มต้น',
    glansHeadSize: 'ขนาดหัว',
    gSmall: 'เล็ก',
    gNormal: 'ปกติ',
    gLarge: 'ใหญ่',
    // graphic (2D/3D) labels — i18n so EN mode is fully translated
    g2dAria: 'ภาพประกอบมุมมองด้านข้างและภาพตัดขวาง ก่อนและหลังการฉีดฟิลเลอร์',
    g2dSide: 'มุมมองด้านข้าง',
    g2dCross: 'ภาพตัดขวาง (ลำตัว)',
    g2dLegShaft: '🔴 ลำตัวขยายตามปริมาณฟิลเลอร์ลำตัว',
    g2dLegGlans: '🟠 ส่วนหัวขยายตามปริมาณฟิลเลอร์ส่วนหัว',
    g2dLegKey: 'เส้นประแดง = หลังฉีด · เส้นประจาง = เดิม',
    g2dDashToggleHint: 'เส้นประ · กดเพื่อ เปิด/ปิด',
    g2dToggleAfter: 'หลังฉีด',
    g2dToggleBaseline: 'เดิม',
    model3dAria: 'แบบจำลองสามมิติ ลากเพื่อหมุน',
  },
  en: {
    title: 'Penile Filler Size Estimator',
    sub: 'Adjust the parameters below to estimate the approximate dimensions following dermal-filler augmentation. All figures are illustrative estimates to help visualize the outcome more clearly.',
    adjust: 'Parameters',
    length: 'Length',
    baseSize: 'Baseline size (shaft girth)',
    condomMode: 'Select condom size',
    diaMode: 'Set diameter',
    totalFiller: 'Total filler volume',
    splitLabel: 'Injection split: shaft / glans',
    shaft: 'Shaft',
    glans: 'Glans',
    graphic: 'Illustration',
    view2d: '2D anatomical',
    view3d: '3D (rotatable)',
    rotateHint: 'Drag to rotate · scales with the specified volume in real time',
    resultsHeader: 'Estimated dimensions (baseline → post-injection)',
    resGirth: 'Girth (shaft)',
    resDia: 'Diameter',
    resCondom: 'Recommended condom size',
    recommended: 'Recommended',
    pickClosest: 'pick the condom closest to this',
    resLength: 'length (flaccid)',
    lengthWarn: 'anti-retraction splint, not true elongation',
    reviewBtn: 'Real reviews',
    reviewBtnSub: 'real before–after cases',
    reviewTitle: 'Real case reviews',
    reviewSub: 'pick which to view · real before–after',
    refsBtn: 'Research references',
    refsBtnSub: 'sources behind the math',
    refsTitle: 'Research behind the calculations',
    refsSub: 'Every formula is grounded in published medical research — tap a card to open the original paper',
    refsUsed: 'used for',
    refsNote: 'All values are illustrative estimates · every source was verified at publication time (2026)',
    reviewCircum: 'Circumcised',
    reviewNocircum: 'Uncircumcised',
    resGlans: 'Glans size',
    before: 'baseline',
    noCondomEffect: 'does not affect condom size',
    sizesUnit: 'sizes',
    sameSize: 'unchanged',
    beyondStd: 'beyond standard 🔥',
    rangeLegend: 'left = durable (ระยะคงตัว) · right = peak/early (ขนาดใหญ่ที่สุด)',
    note: 'Filler increases girth and glans dimensions · adds ~+1.6cm FLACCID length (an anti-retraction splint, not true elongation) · a shorter shaft yields a greater girth increase for the same volume · persists ~12–18 months then gradually resorbs · condom size references the shaft girth · all values are estimates ±~1cm',
    disclaimer: 'All illustrations and figures are illustrative estimates provided for educational reference only and do not constitute a guarantee of results. Actual outcomes vary between individuals, depending on skin elasticity, filler volume, and injection technique. Hyaluronic-acid filler is naturally resorbable. Please consult a qualified physician before making any decision.',
    unitCm: 'cm',
    unitIn: 'in',
    cc: 'cc',
    glansBase: 'Initial glans size',
    glansHeadSize: 'Head size',
    gSmall: 'Small',
    gNormal: 'Normal',
    gLarge: 'Large',
    g2dAria: 'Side-view and cross-section illustration, before and after filler',
    g2dSide: 'Side view',
    g2dCross: 'Cross-section (shaft)',
    g2dLegShaft: '🔴 Shaft expands with shaft filler',
    g2dLegGlans: '🟠 Glans expands with glans filler',
    g2dLegKey: 'Red dashed = after · faint dashed = baseline',
    g2dDashToggleHint: 'dashed · tap to toggle',
    g2dToggleAfter: 'after',
    g2dToggleBaseline: 'baseline',
    model3dAria: '3D model — drag to rotate',
  },
};

export function makeT(lang) {
  const dict = STRINGS[lang] || STRINGS.th;
  return (key) => (dict[key] != null ? dict[key] : (STRINGS.th[key] != null ? STRINGS.th[key] : key));
}
