#!/usr/bin/env python3
"""Generate .agents/index/repo-tree.md from the current repository tree."""
from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
from tempfile import NamedTemporaryFile
from typing import Iterable

DEFAULT_EXCLUDED_NAMES = {
    ".agents",
    ".git",
    ".next",
    ".venv",
    ".cache",
    ".idea",
    ".mypy_cache",
    ".pytest_cache",
    ".vscode",
    "__pycache__",
    "build",
    "coverage",
    "dist",
    "logs",
    "node_modules",
    "tmp",
    "venv",
}

DEFAULT_IMPORTANT_TOP_LEVEL = {
    "agents.sh",
    "app",
    "docker-compose.yml",
    "Makefile",
    "package.json",
    "pyproject.toml",
    "scripts",
    "src",
    "tests",
    "web",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate .agents/index/repo-tree.md from the current repository tree."
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("."),
        help="Repository root to scan (default: current directory).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(".agents/index/repo-tree.md"),
        help="Output markdown file path.",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=4,
        help="Maximum traversal depth from root (default: 4).",
    )
    return parser.parse_args()


def should_exclude(path: Path, excluded_names: set[str]) -> bool:
    return path.name in excluded_names


def sorted_children(path: Path, excluded_names: set[str]) -> list[Path]:
    try:
        children = [child for child in path.iterdir() if not should_exclude(child, excluded_names)]
    except OSError:
        return []

    return sorted(children, key=lambda child: (not child.is_dir(), child.name.lower()))


def format_tree_lines(root: Path, max_depth: int, excluded_names: set[str]) -> list[str]:
    lines = ["."]

    def walk(current: Path, prefix: str, depth: int) -> None:
        if depth >= max_depth:
            return

        children = sorted_children(current, excluded_names)
        total = len(children)

        for index, child in enumerate(children):
            is_last = index == total - 1
            branch = "└── " if is_last else "├── "
            display_name = f"{child.name}/" if child.is_dir() else child.name
            lines.append(f"{prefix}{branch}{display_name}")

            if child.is_dir():
                child_prefix = "    " if is_last else "│   "
                walk(child, prefix + child_prefix, depth + 1)

    walk(root, prefix="", depth=0)
    return lines


def collect_important_top_level(root: Path, excluded_names: set[str]) -> list[str]:
    items = sorted_children(root, excluded_names)
    result: list[str] = []

    for item in items:
        if item.name in DEFAULT_IMPORTANT_TOP_LEVEL:
            marker = f"`{item.name}/`" if item.is_dir() else f"`{item.name}`"
            result.append(marker)

    if result:
        return result

    return [f"`{item.name}/`" if item.is_dir() else f"`{item.name}`" for item in items]


def render_markdown(
    *,
    generated_at: str,
    root_display: str,
    max_depth: int,
    excluded_names: Iterable[str],
    tree_lines: list[str],
    important_top_level: list[str],
    generator_path: str,
) -> str:
    excluded_block = "\n".join(f"- `{name}`" for name in sorted(excluded_names))
    tree_block = "\n".join(tree_lines)
    important_block = "\n".join(f"- {item}" for item in important_top_level)

    return f"""# Repository Tree

Generated at: {generated_at}
Generated by: `{generator_path}`

## Scope
- Root: `{root_display}`
- Max depth: {max_depth}

## Excluded
{excluded_block}

## Tree
```text
{tree_block}
```

## Important Top-Level Areas
{important_block}

## Notes
This file is generated from the current filesystem state.
`.agents/` is intentionally excluded.
Do not manually maintain this file unless debugging the generator.
"""


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    with NamedTemporaryFile("w", encoding="utf-8", delete=False, dir=path.parent) as handle:
        handle.write(content)
        temp_path = Path(handle.name)

    temp_path.replace(path)


def main() -> None:
    args = parse_args()

    root = args.root.resolve()
    if not root.exists():
        raise SystemExit(f"Repository root does not exist: {root}")

    output = args.output
    if not output.is_absolute():
        output = root / output

    excluded_names = set(DEFAULT_EXCLUDED_NAMES)
    generated_at = datetime.now().astimezone().isoformat(timespec="seconds")
    tree_lines = format_tree_lines(root, args.max_depth, excluded_names)
    important_top_level = collect_important_top_level(root, excluded_names)

    content = render_markdown(
        generated_at=generated_at,
        root_display=".",
        max_depth=args.max_depth,
        excluded_names=excluded_names,
        tree_lines=tree_lines,
        important_top_level=important_top_level,
        generator_path="scripts/update_repo_context.py",
    )

    atomic_write(output, content)
    print(f"Generated: {output}")


if __name__ == "__main__":
    main()
